---
####################
# Install GNU Stow #
####################
- include: stow.yml

######################
# Available Packages #
######################
# Installs: libevent, ncurses, tmux
- include: tmux.yml
- include: openssl.yml # Because cryptography
- include: expat.yml   # Needed for git
